server:
  #服务器上传文件需要更换ip
  #生产
  ip: 34.88.124.218
#  #测试
#  ip: localhost
  port: 9090
#  ssl:
#    key-alias: tomcat
#    key-store-password: o4w93t7n
#    key-store-type: PKCS12
#    key-store: classpath:www.aurexp.com.pfx


spring:
  datasource:
#    #测试
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/rucn?characterEncoding=utf8
#    username: root
#    password: 123456
    #生产
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://free1.mysql.database.azure.com/rucn?characterEncoding=utf8&useSSL=true&requireSSL=true
    username: root_azure
    password: Qq5515150

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    email: jarvis_server@163.com
    host: smtp.163.com
    port: 465
    username: jarvis_server
    password: GIEGXBMCMFCHLCPK
    sender: Aurexp
  redis:
    host: 34.88.124.218
    port: 6379
    password: EGXBMCMFCHL
#    host: localhost

mybatis:
  mapper-locations: classpath:mapper/*.xml  #????mybatis?xml??
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
#    #测试
#    path: D:\pro\Transportation\src\main\resources\files\
#    cache: D:\pro\Transportation\src\main\resources\cache\
    #生产
    path: /home/wenxuecheng0708/server/springboot/files/
    cache: /home/wenxuecheng0708/server/springboot/cache/


code:
  expiration: 300